### ISSUE TITLE
Data Sources

### ISSUE THREAD

**Issue by yalsaffar** [yalsaffar/Tourism-Recommendation-System#1]
This issue is made to establish the fundamental information for the data sources, types, and importance.

Note: keep in mind that data has to cover the three main Recos intended to be developed.
 
- Defining the main Country for Implementing the solution
- Establish the main sources of data
- Clarify the exact type of data to be used(explicit or Implicit). It has to follow the business proposal. 
-  As the Recos are dependent on each other, establish the hierarchy of data(which reco will introduce an input for the next reco)

This issue should be covered by **Majd**, **Rabindra,** And **Yousif Alsaffar**. More detailed issues would be considered separately.

**Comment by browncena2020** [comment]
For simplicity sake, let's just do Madrid? That way we'll at least know the city and the spots that the engine recommends better and we can find errors easier

**Comment by yalsaffar** [comment]
@browncena2020 okay sounds good for now, let's start by defining these datasets, and focus on the data about flights to and from Madrid Airport as a starting point.

**Comment by yalsaffar** [comment]
@majdbar321 **@Rabindra** check this out, it might be useful:
[https://www.kaggle.com/datasets/efehandanisman/skytrax-airline-reviews](Kaggle)

**Comment by majdbar321** [comment]
will do, Thanks!!
