### ISSUE TITLE
Hotel Data

### ISSUE THREAD

**Issue by majdbar321** [yalsaffar/Tourism-Recommendation-System#13]
@yalsaffar I will start to look for hotel data in Madrid, and with the help of @0ardneebwar0 we will clean the data and make sure it is ready for the hotel reco system. I will let you know as soon as we find the suitable data and clean it.

**Comment by yalsaffar** [comment]
Amazing! Keep me updated on how it will go.
I have found a tool to scrape Airbnb data and I will update you here on how it will go.

**Comment by majdbar321** [comment]
@yalsaffar and @0ardneebwar0  I have found a website that has the quarterly Airbnb data for the last year for each region for free. This is the website [http://insideairbnb.com/get-the-data](url)

**Comment by yalsaffar** [comment]
Wow, this is perfect! it's exactly what we need

**Comment by majdbar321** [comment]
Data cleaning is done I uploaded the files to the airbnb_branch. However, there are some files that exceeded the limit of github so I just removed them but later I will add such files with the gitignore.
