### ISSUE TITLE
Member githubs

### ISSUE THREAD

**Issue by miguelgfierro** [yalsaffar/Tourism-Recommendation-System#9]
hey team, it is not clear to me who is who on this project. 

I can identify Yousif @yalsaffar and Majd @majdbar321, however, I don't know which user is Saad, Youssef, Lorentz, Rabindra.

As personal advice, it would be good for you and for your future job search to have a strong GitHub profile.

**Comment by yalsaffar** [comment]
Thank you for raising this concern. I understand that our previous work did not effectively demonstrate who was responsible for which contribution, and I apologize for any confusion this may have caused.

To address this issue, we will make a conscious effort to ensure that our future contributions are clearly attributed to each team member. We recognized the importance of proper attribution in collaborative projects, and we are committed to improving our practices to reflect this.

**Comment by miguelgfierro** [comment]
@yalsaffar Can you please list the mapping between each person and their github?

**Comment by yalsaffar** [comment]
Yes sure, here it is:
@majdbar321 Majd Barghouthi
@browncena2020 Saad Sahir
@ygebaly22 Youseef Ahmed
@lochhonest Lorenz Ehrlich
@0ardneebwar0 Rabindra Adhikari

**Comment by miguelgfierro** [comment]
Thanks
